name: Run Benchmark tests

on:
  push:
    branches: [main, "release/*"]
  pull_request:
    branches: [main, "release/*"]

defaults:
  run:
    shell: bash

jobs:
  benchmark:
    runs-on: ubuntu-latest

    timeout-minutes: 30

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Step 3: Cache pip dependencies
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Step 4: Install Dependencies
      - name: Install Dependencies
        run: |
          find . -name 'requirements.txt' -exec sh -c 'if [ -s {} ]; then pip install -r {}; fi' \;

      - name: Embedding Performance Test
        run: export PYTHONPATH=$PWD # && python embeddings-api/tests/main.py
