name: CI Testing

on:
  push:
    branches: [main, "release/*"]
  pull_request:
    branches: [main, "release/*"]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Step 3: Cache pip dependencies
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          find . -name 'requirements.txt' -exec sh -c 'pip install -r {}' \;

      # Step 5: Install Ruff for linting
      - name: Install Ruff
        run: |
          source venv/bin/activate
          pip install ruff

      # Step 6: Run Ruff for linting
      - name: Run Ruff Lint
        run: |
          source venv/bin/activate
          ruff check --show-fixes

      # Step 7: Discover and test all folders
      - name: Discover and test all folders
        run: |
          source venv/bin/activate
          for folder in $(find . -type d -mindepth 1 -maxdepth 1 ! -name '.*'); do
            echo "Processing $folder"

            # Run tests if test files are present
            if [ -n "$(find "$folder" -name "test*.py")" ]; then
              echo "Running tests in $folder"
              pytest "$folder" --disable-warnings
            else
              echo "No tests found in $folder"
            fi
          done
