name: CI Testing

on:
  push:
    branches: [main, "release/*"]
  pull_request:
    branches: [main, "release/*"]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/ruff-action@v3

  test-examples:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
        example:
          [
            chatterbox-tts,
            deepseek-r1,
            embeddings-api,
            image-recognition-api,
            modernbert-embed,
            rfdetr-object-detection,
            whisper-stt-api,
          ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install uv and set Python version ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v6
        with:
          activate-environment: true
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: Install dependencies
        run: uv pip install -r ${{ matrix.example }}/requirements.txt

      - name: Start server
        run: |
          cd ${{ matrix.example }}
          uv run python server.py &
          SERVER_PID=$!
          echo "SERVER_PID=$SERVER_PID" >> $GITHUB_ENV
          sleep 10

      - name: Run client test
        run: |
          cd ${{ matrix.example }}
          if [ -f test.sh ]; then sh test.sh; else uv run python client.py; fi

      - name: Stop server
        run: |
          kill $SERVER_PID || true
